# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d899e101be137b729d060e5cec4253a293177ed7296d5435764cdd32180ed4a9eab6ce7bfc24b3132c4bc8b13126a4312560ecd9d6d73b8e969f4bd2288193a

test:
  secret_key_base: 5073a2b96fe586a95c49ea1bbc4443c4b88e8e4e52acd65dd4eaa3e0ce0c6f8c481e59ae80d42127b479c8ff8d7c6096a35b54cb080add9bbe79d0df62e39290

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
